*&---------------------------------------------------------------------*
*& Modulpool SAPBC414_TRAVELAG_T
*&---------------------------------------------------------------------*


INCLUDE ZTRAVELAG_A18_TTOP.
*INCLUDE BC414_TRAVELAG_TTOP.
INCLUDE ZTRAVELAG_A18_TF01.
*INCLUDE BC414_TRAVELAG_TF01.
INCLUDE ZTRAVELAG_A18_TO01.
*INCLUDE BC414_TRAVELAG_TO01.
INCLUDE ZTRAVELAG_A18_TI01.
*INCLUDE BC414_TRAVELAG_TI01.
INCLUDE ZTRAVELAG_A18_TE01.
*INCLUDE BC414_TRAVELAG_TE01.
